services:
  db:
      image: mysql:5.7
      volumes:
        - "./.data/db:/var/lib/mysql"
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: DulzuraDataBase
          MYSQL_USER: user
          MYSQL_PASSWORD: machines1
      ports:
        - 33060:3306